Application.TourAndTravel.Web/Models/PackagesVM/PackageTypeByAdmin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Application.TourAndTravel
{
    public class PackageTypeByAdmin
    {
        [Key]
        public long PackageTypeID { get; set; }

        public string PackageName  { get; set; }

        public string PlaceName { get; set; }

        public decimal PackagePrice { get; set; }

        public string PackageDescription { get; set; }

        public string Duretion { get; set; }

        public string PackageInclusions { get; set; }
        public string PackageInclusions1 { get; set; }
        public string Day1 { get; set; }
        public string Day2 { get; set; }
        public string Day3 { get; set; }
        public string Day4 { get; set; }
        public string Day5 { get; set; }
        public string Day6 { get; set; }
        public string Day7 { get; set; }
        public string Day8 { get; set; }
        public string Day9 { get; set; }
        public string Day10 { get; set; }

        public string TermAndCondition { get; set; }

        public string Image { get; set; }
        

        public bool IsDelete { get; set; }

        public string CreatedBy { get; set; }

        public DateTime CreatedDate { get; set; }

        public string ModifiedBy { get; set; }

        public DateTime ModifiedDate { get; set; }

        public string PackageType { get; set; }

    }

}

Application.TourAndTravel.Web/Controllers/adminController.cs
using Application.TourAndTravel.Web.Models;
using Application.TourAndTravel.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Application.TourAndTravel.Web.Controllers
{
    //[Authorize]
    public class adminController : Controller
    {
        private readonly DBAccessVM dBAccessVM;
        private readonly PackageRepositories _packageRepositories;
        private readonly RechargeRepositories _rechargeRepositories;
        private string _fileName = string.Empty;
        public adminController()
        {
            _packageRepositories = new PackageRepositories();
            _rechargeRepositories = new RechargeRepositories();
            dBAccessVM = new DBAccessVM();
        }
        private string GetLoggedInUser()
        {
            string userName = string.Empty;
            if (User.Identity.IsAuthenticated) { userName = User.Identity.Name; }
            return userName;
        }
        // GET: admin
        public ActionResult Dashboard()
        {
            string userName = GetLoggedInUser();
            if (!string.IsNullOrEmpty(userName))
                return View();
            else
                return RedirectToAction("Login", "Account");
        }
        [HttpGet]
        public ActionResult PackageTypeByAdmin(int? packageTypeID)
        {
            string userName = GetLoggedInUser();
            if (!string.IsNullOrEmpty(userName))
            {
                ParaglidingDetails coll = null;
                if (packageTypeID != null)
                {
                    coll = _packageRepositories.getPackageTypeDataById(packageTypeID);
                    if (coll != null)
                        return View(coll);
                }
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        [HttpPost]
        public ActionResult PackageTypeByAdmin(ParaglidingDetails paraglidingDetails, HttpPostedFileBase Image)
        {
            string userName = GetLoggedInUser();
            if (!string.IsNullOrEmpty(userName))
            {
                string ImageName = string.Empty;
                if (paraglidingDetails.PackageTypeID == 0)
                {
                    ImageName = GetImage(Image);
                    if (ImageName != null)
                    {
                        paraglidingDetails.Image = ImageName;
                        paraglidingDetails.CreatedBy = userName;
                        paraglidingDetails.ModifiedBy = "";
                        int i = _packageRepositories.PackageTypeByAdminsave(paraglidingDetails);
                        TempData["msg"] = "Save Successfully";
                    }
                    else
                    {
                        TempData["msg"] = "Image size must be less than or equal to 300KB";
                    }

                }
                else
                {
                    ImageName = GetImage(Image);
                    paraglidingDetails.Image = ImageName;
                    paraglidingDetails.ModifiedBy = userName;
                    int i = _packageRepositories.UpdatePackageTypeDataById(paraglidingDetails, out _fileName);
                    var filePath = Server.MapPath("~/img/" + _fileName);
                    if (System.IO.File.Exists(filePath))
                    {
                        System.IO.File.Delete(filePath);
                    }
                    TempData["msg"] = "Information updated Successfully";
                }
                return RedirectToAction("PackageTypeByAdmin");
            }
            else
            {
                return RedirectToAction("Login","Account");
            }
               
        }

        private string GetImage(HttpPostedFileBase Image)
        {
            string ImageName = string.Empty;
            Random rnd = new Random();
            var extensions = "";
            var allowExtensions = new[]
            {
                ".jpg",".Jpg",".png",".jpeg"
            };
            if (Image != null)
            {
                extensions = Path.GetExtension(Image.FileName);
            }
            if (allowExtensions.Contains(extensions))
            {
                int filelength = 0;
                filelength = Image.ContentLength;
                if (filelength > 307200)
                {
                    return ImageName = null;
                }
                else
                {
                    string filename = "";
                    filename = Image.FileName;
                    var dt = DateTime.Now.ToString("ddmmyyyy");
                    if (extensions == ".jpg")
                    {
                        var pp7 = rnd.Next(4, 9999).ToString();
                        Image.SaveAs(HttpContext.Server.MapPath("~/img/") + pp7 + dt + ".jpg");
                        ImageName = pp7 + dt + ".jpg";
                        return ImageName;
                    }
                    else if (extensions == ".jpeg")
                    {
                        var pp7 = rnd.Next(4, 9999).ToString();
                        Image.SaveAs(HttpContext.Server.MapPath("~/img/") + pp7 + dt + ".jpeg");
                        ImageName = pp7 + dt + ".jpeg";
                        return ImageName;
                    }
                    else if (extensions == ".Jpg")
                    {
                        var pp7 = rnd.Next(4, 9999).ToString();
                        Image.SaveAs(HttpContext.Server.MapPath("~/img/") + pp7 + dt + ".Jpg");
                        ImageName = pp7 + dt + ".Jpg";
                        return ImageName;
                    }
                    else if (extensions == ".png")
                    {
                        var pp7 = rnd.Next(4, 9999).ToString();
                        Image.SaveAs(HttpContext.Server.MapPath("~/img/") + pp7 + dt + ".png");
                        ImageName = pp7 + dt + ".png";
                        return ImageName;
                    }
                    else
                    {
                        return ImageName = null;
                    }
                }
            }
            else
            {
                return ImageName = null;
            }
        }

        [HttpGet]
        public ActionResult List_PackageTypeByAdmin()
        {
            return View();
        }
        [HttpGet]
        public ActionResult deletePackageTypeByAdmin(int? packageTypeID)
        {
            int i = 0;
            if (packageTypeID != null)
            {
                i = _packageRepositories.DeletePackageTypeByAdminsave(packageTypeID);
                if (i > 0)
                {
                    TempData["msg"] = "Data Delete Succeccfully....";
                }
                else
                {
                    TempData["msg"] = "! there is problem no data delete";
                }
            }
            return RedirectToAction("List_PackageTypeByAdmin");
        }

        [HttpGet]
        public ActionResult RechargeByAdmin(int? rechargeID)
        {
            RechargeInfo coll = null;
            var list = dBAccessVM.travellerRegistration.ToList();
            if (rechargeID != null)
            {
                coll = _rechargeRepositories.getRechargeTypeDataById(rechargeID);
                if (coll != null)
                {
                    ViewBag.Companies = list;
                    return View(coll);
                }
                else
                {
                    ViewBag.Companies = list;
                    return View();
                }
            }
            else
            {
                ViewBag.Companies = list;
                return View();
            }
        }

        [HttpPost]
        public ActionResult RechargeByAdmin(RechargeInfo rechargeInfo)
        {
            
            WalletCRDRHistory walletCRDR = new WalletCRDRHistory();
            string userName = GetLoggedInUser();
            if(!string.IsNullOrEmpty(userName))
            {
                if (rechargeInfo.RechargeID == 0)
                {
                    rechargeInfo.CreatedBy = userName;
                    rechargeInfo.IsDelete = true;
                    int i = _rechargeRepositories.RechargeInfiSave(rechargeInfo);
                    walletCRDR.Credit = Convert.ToDecimal(rechargeInfo.WalletBalance);
                    walletCRDR.Debit = 0;
                    walletCRDR.TravellerEmail = rechargeInfo.TravelAgentEmail;
                    walletCRDR.CreditDebitDate = System.DateTime.Now;
                    dBAccessVM.walletCRDRHistories.Add(walletCRDR);
                    dBAccessVM.SaveChanges();
                    TempData["msg"] = "Save Successfully....";
                    return RedirectToAction("RechargeByAdmin");
                }
                else
                {
                    rechargeInfo.ModifiedBy = userName;
                    int i = _rechargeRepositories.UpdateRechargeInfo(rechargeInfo);
                    walletCRDR.Credit = Convert.ToDecimal(rechargeInfo.WalletBalance);
                    walletCRDR.Debit = 0;
                    walletCRDR.TravellerEmail = rechargeInfo.TravelAgentEmail;
                    walletCRDR.CreditDebitDate = System.DateTime.Now;
                    dBAccessVM.walletCRDRHistories.Add(walletCRDR);
                    dBAccessVM.SaveChanges();
                    TempData["msg"] = "Update Successfully....";
                    return RedirectToAction("RechargeByAdmin");
                }
            }
            else
            {
                return RedirectToAction("Login","Account");
            }
        }
        [HttpGet]
        public ActionResult ListRechargeByAdmin()
        {
            return View();
        }
        [HttpGet]

Application.TourAndTravel.Web/Views/admin/LeadBookingInfo.cshtml
@using Application.TourAndTravel.Web.Models
@{
    DBAccessVM dal = new DBAccessVM();
}
@{
    ViewBag.Title = "LeadBookingInfo";
    Layout = "~/Views/Shared/_TravellerLayout.cshtml";
}

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-bd lobidrag">
            <div class="panel-heading">
                <div class="btn-group" id="buttonexport">
                    <a href="#">
                        <h4>Lead Information</h4>
                    </a>
                </div>
            </div>
            <div class="panel-body">
                <!-- Plugin content:powerpoint,txt,pdf,png,word,xl -->
                <div class="btn-group">
                    <div class="buttonexport" id="buttonlist">
                        @*<a class="btn btn-add">
                                <i class="fa fa-plus"></i> Lead Information
                            </a>*@
                    </div>
                </div>
                <!-- Plugin content:powerpoint,txt,pdf,png,word,xl -->
                <div class="table-responsive">
                    <table id="dataTableExample1" class="table table-bordered table-striped table-hover">
                        <thead>
                            <tr class="info">
                                <th>SL</th>
                                <th>Name</th>
                                <th>Mobile</th>
                                <th>Email</th>
                                <th>No Of Pax</th>
                                <th>Duration</th>                                                              
                                <th>Message</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int sr = 0;
                            }
                            @{
                                var coll = dal.bookingInfo.ToList();
                                foreach (var m in coll)
                                {
                                    <tr>
                                        <td>@{sr++;}@sr</td>
                                        <td>@m.ClientName</td>
                                        <td>@m.MobileNo</td>
                                        <td>@m.Email</td>
                                        <td>@m.NoOfPax</td>                                       
                                        <td>@m.Duration</td>
                                        <td>@m.message</td>
                                        @*<td><span class="label-custom label label-default">Active</span></td>*@

                                    </tr>
                                }
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Application.TourAndTravel.Web/Views/admin/ListRechargeByAdmin.cshtml
@using Application.TourAndTravel.Web.Models
@{
    DBAccessVM dal = new DBAccessVM();
}
@{
    ViewBag.Title = "ListRechargeByAdmin";
    Layout = "~/Views/Shared/_TravellerLayout.cshtml";
}

        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-bd lobidrag">
                    <div class="panel-heading">
                        <div class="btn-group" id="buttonexport">
                            <a href="#">
                                <h4>Recharge Information</h4>
                            </a>
                        </div>
                    </div>
                    <div class="panel-body">
                        <!-- Plugin content:powerpoint,txt,pdf,png,word,xl -->
                        <div class="btn-group">
                            <div class="buttonexport" id="buttonlist">
                                <a class="btn btn-add" href="/admin/RechargeByAdmin/">
                                        <i class="fa fa-plus"></i> Recharge
                                    </a>
                            </div>
                            @if (TempData["msg"] != null)
                            {
                                <div class="alert alert-sm alert-success alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                                    <i class="fa fa-check"></i><strong>Information !</strong> @TempData["msg"]
                                </div>
                            }
                        </div>
                        <!-- Plugin content:powerpoint,txt,pdf,png,word,xl -->
                        <div class="table-responsive">
                            <table id="dataTableExample1" class="table table-bordered table-striped table-hover">
                                <thead>
                                    <tr class="info">
                                        <th>SL</th>
                                        <th>Company Name</th>
                                        <th>Agent Name</th>
                                        <th>Agent Email</th>
                                        <th>Wallet Balance</th>
                                        <th>Created Date</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        int sr = 0;
                                    }@{
                                        var coll = dal.Recharge.Where(a => a.IsDelete == true).ToList();
                                        foreach (var m in coll)
                                        {
                                            string comapnyName = dal.travellerRegistration.Where(a => a.TravellerID == m.TravellerID).Select(a => a.TravellerCompanyName).FirstOrDefault();
                                            <tr>
                                                <td>@{sr++;}@sr</td>
                                                <td>@comapnyName</td>
                                                <td>@m.TravelAgentName</td>
                                                <td>@m.TravelAgentEmail</td>
                                                <td>@m.WalletBalance</td>
                                                <td>@m.CreatedDate</td>
                                                <td>
                                                    <span class="label-custom label label-default">
                                                        @if (m.IsDelete == true)
                                                        {
                                                            <span>Yes</span>
                                                        }
                                                        else
                                                        {
                                                            <span>No</span>
                                                        }
                                                </span>
                                            </td>

                                            <td>
                                                <a href="@Url.Action("RechargeByAdmin", "admin", new { rechargeID = m.RechargeID })" class="btn btn-xs btn-info"><i class="fa fa-pencil-square"></i></a>
                                                <a href="@Url.Action("DeleteRechargeInfo", "admin", new { rechargeID = m.RechargeID })" class="btn btn-xs btn-danger"><i class="fa fa-trash-o"></i></a>
                                                @if (m.IsDelete == true)
                                                {
                                                    <a href="@Url.Action("activate", "admin", new { rechargeID = m.RechargeID })" class="btn btn-xs btn-danger"><i class="fa fa-times"></i></a>
                                                }
                                                else
                                                {
                                                    <a href="@Url.Action("activate", "admin", new { rechargeID = m.RechargeID })" class="btn btn-xs btn-primary"><i class="fa fa-check-square"></i></a>
                                                }
                                            </td>
                                        </tr>
                                    }
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

Application.TourAndTravel.Web/Views/admin/List_PackageTypeByAdmin.cshtml
@using Application.TourAndTravel.Web.Models
@{
    DBAccessVM dal = new DBAccessVM();
}
@{
    ViewBag.Title = "List_PackageTypeByAdmin";
    Layout = "~/Views/Shared/_TravellerLayout.cshtml";
}

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-bd lobidrag">
            <div class="panel-heading">
                <div class="btn-group" id="buttonexport">
                    <a href="/admin/PackageTypeByAdmin">
                        <h4>Add Package</h4>
                    </a>
                </div>
            </div>
            <div class="panel-body">
                <!-- Plugin content:powerpoint,txt,pdf,png,word,xl -->
                <div class="btn-group">
                    <div class="buttonexport" id="buttonlist">
                        <a class="btn btn-add" href="/admin/PackageTypeByAdmin/">
                            <i class="fa fa-plus"></i> Add Package
                        </a>
                    </div>
                    @*<button class="btn btn-exp btn-sm dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bars"></i> Export Table Data</button>*@
                    @*@if (TempData["msg"] != null)
                    {
                        <div class="alert alert-sm alert-success alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                            <i class="fa fa-check"></i><strong>Information !</strong> @TempData["msg"]
                        </div>
                    }*@

                </div>
                <!-- Plugin content:powerpoint,txt,pdf,png,word,xl -->
                <div class="table-responsive">
                    <table id="dataTableExample1" class="table table-bordered table-striped table-hover">
                        <thead>
                            <tr class="info">
                                <th>Sr</th>
                                <th>Image</th>
                                <th>Package Name </th>
                                <th>Place Name</th>
                                <th>Duretion(Days / Night)</th>
                                <th>Price</th>
                                <th>Last Modified</th>
                                <th>IsActive</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int sr = 0;
                            }
                            @{
                                var coll = dal.paraglidingDetails.Where(a => a.IsDelete == true).ToList();
                                //var coll = dal.PackagesByAdmin.ToList();
                                foreach (var m in coll)
                                {
                                    <tr>
                                         <td>@{sr++;}@sr</td>
                                        <td><img src="~/img/@m.Image" class="img-circle" alt="User Image" width="50" height="50"> </td>
                                        <td>@m.PackageName </td>
                                        <td>@m.PlaceName</td> 
                                         <td>@m.Duretion</td> 
                                        <td><i class="fa fa-inr"></i> @m.PackagePrice</td>                                      
                                        <td>@m.ModifiedDate.ToString("dd MMM, yyyy")</td>
                                        <td>
                                            <span class="label-custom label label-default">
                                                @if (m.IsDelete == true)
                                                {
                                                    <span>Yes</span>
                                                }
                                                else
                                                {
                                                    <span>No</span>
                                                }
                                        </span>
                                    </td>
                                    <td>
                                        <a href="@Url.Action("PackageTypeByAdmin","admin", new { packageTypeID=m.PackageTypeID})" class="btn btn-xs btn-info"><i class="fa fa-pencil-square"></i></a>
                                        <a href="@Url.Action("deletePackageTypeByAdmin","admin", new { packageTypeID=m.PackageTypeID})" class="btn btn-xs btn-danger"><i class="fa fa-trash-o"></i></a>
                                    </td>
                                </tr>
                            }

                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Application.TourAndTravel.Web/Views/admin/RechargeByAdmin.cshtml
@model Application.TourAndTravel.RechargeInfo
@{
    ViewBag.Title = "RechargeByAdmin";
    Layout = "~/Views/Shared/_TravellerLayout.cshtml";
}

        <div class="row">
            @if (TempData["msg"] != null)
            {
                <div class="alert alert-sm alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <i class="fa fa-check"></i><strong>Information !</strong> @TempData["msg"]
                </div>
            }
            <!-- Form controls -->
            <div class="col-sm-12">
                <div class="panel panel-bd lobidrag">
                    <div class="panel-heading">
                        <div class="btn-group" id="buttonlist">
                            <a class="btn btn-add " href="/admin/ListRechargeByAdmin">
                                <i class="fa fa-list"></i> Recharge List
                            </a>
                        </div>
                    </div>
                    <div class="panel-body">
                        @using (Html.BeginForm("RechargeByAdmin", "admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.ValidationSummary(true)
                            @Html.HiddenFor(m => m.RechargeID)
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label>Company Name</label>
                                        @Html.DropDownListFor(m => m.TravellerID,new SelectList(ViewBag.Companies,"TravellerID","TravellerCompanyName"),"--Select Comapny--" ,new { @class = "form-control", @placeholder = "Company Name", @required = "" })
                                        @Html.ValidationMessageFor(m => m.TravellerID, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label>Travel Agent Name</label>
                                        @Html.TextBoxFor(m => m.TravelAgentName, new { @class = "form-control", @placeholder = "Travel Agent Name", @required = "",@readonly="readonly" })
                                        @Html.ValidationMessageFor(m => m.TravelAgentName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label>Travel Agent Email</label>
                                        @Html.TextBoxFor(m => m.TravelAgentEmail, new { @class = "form-control", @placeholder = "Travel Agent Email", @required = "",@readonly="readonly" })
                                        @Html.ValidationMessageFor(m => m.TravelAgentEmail, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                              
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label>Credit</label>
                                        @Html.TextBoxFor(m => m.WalletBalance, new { @class = "form-control", @placeholder = "Credit", @required = "" })
                                        @Html.ValidationMessageFor(m => m.WalletBalance, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="reset-button">
                                        <button type="submit" class="btn btn-success  m-t-20">Recharge</button>
                                    </div>
                                </div>
                            </div>
                           
                        }

                    </div>
                        </div>
                    </div>
                </div>
        <script src="~/admin/assets/plugins/jQuery/jquery-1.12.4.min.js"></script>
<script>
    $(document).ready(function () {
        $('#TravellerID').change(function () {
            var travellerID = $(this).val();
            $.get("/Traveller/GetTravellerInfo", { travellerID: travellerID }, function (response) {
                if (response != null) {
                    console.log(response);
                $("#TravelAgentName").val(response.TravellerName);
                $("#TravelAgentEmail").val(response.TravellerEmail);
            }
            else {
                alert("No Data Found");
            }
            });
        })
    })
</script>
            