Application.TourAndTravel.Web/Controllers/TravellerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Application.TourAndTravel.Web.Models;

namespace Application.TourAndTravel.Web.Controllers
{
    
    public class TravellerController : Controller
    {
        private readonly DBAccessVM dBAccess;
        private readonly  TravellerRepositoris _travellerRepositoris;
        public TravellerController()
        {
            _travellerRepositoris = new TravellerRepositoris();
            dBAccess = new DBAccessVM();
        }
        // GET: Traveller
        [HttpGet]
        public ActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SignUp(TravellerRegistration travellerRegistration)
        {
            int i = _travellerRepositoris.TravellerSignUp(travellerRegistration);
            if (i > 0)
            {
                TempData["msg"] = "Your Registration is successfully";
                return RedirectToAction("SignUp");
            }
            else
            {

                TempData["msg"] = "Failed ! Try again";
                return RedirectToAction("SignUp");
            }
        }

        [HttpGet]
        public ActionResult TravellerLogin()
        {
            return View();
        }
        [Authorize]
        [HttpGet]
        public ActionResult Leads()
        {
                List<BookingInfo> bookings = null;
                bookings = _travellerRepositoris.GetAllLeads();
                if (bookings.Count > 0)
                    return View(bookings);
                else
                    return View();
          
        }
        [Authorize]
        [HttpPost]
        public ActionResult SellLead(string leadID)
        {
            try
            {
                if (!string.IsNullOrEmpty(leadID))
                {
                    bool x;
                    bool xy;
                    long leadId = Convert.ToInt32(leadID);
                    string userName = string.Empty;
                    if (User.Identity.IsAuthenticated) { userName = User.Identity.Name; }
                    x = _travellerRepositoris.SellLead(leadId, userName);
                    if (x != true)
                    {
                        _travellerRepositoris.UpdateWallet(userName, 75);
                        TempData["msg"] = "You have successfully purchased your leads and now you can see all the information.";
                        return RedirectToAction("Leads");
                    }
                    else
                    {
                        ViewBag.SoldLeadByUser = "true";
                        TempData["msg"] = "You have already buy this lead, please buy other one.";
                        return RedirectToAction("Leads");
                    }
                }
                else
                {
                    return RedirectToAction("Leads");
                }
            }
            catch(Exception ex)
            {
                TempData["msg"]= ex.Message.ToString();
                return RedirectToAction("Leads");
            }
            
            
        }

        [Authorize]
        [HttpGet]
        public ActionResult MyLeads()
        {
            string userName = string.Empty;
            if (User.Identity.IsAuthenticated) { userName = User.Identity.Name; }
            List<BookingInfo> myleads = null;
            myleads = _travellerRepositoris.GetMyLeads(userName);
            if (myleads != null)
                return View(myleads);
            else
                return View();
        }

        [HttpGet]
        public ActionResult GetTravellerInfo(int? travellerID)
        {
            GetCompaniesVM getCompanies = new GetCompaniesVM();
            if (travellerID!=0 && travellerID!=null)
            {
                var data = dBAccess.travellerRegistration.Where(a => a.TravellerID == travellerID).FirstOrDefault();
                getCompanies.TravellerName = data.TravellerName;
                getCompanies.TravellerEmail = data.TravellerEmail;
                return (ActionResult)this.Json((object)getCompanies, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return (ActionResult)this.Json((object)getCompanies, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpGet]
        public ActionResult AddPackage(int? packageID)
        {
            Packages coll = null;
            if (packageID != null)
            {
                coll = _travellerRepositoris.getAddPackageID(packageID);
                if (coll != null)
                    return View(coll);
                else
                    return View();
            }
            return View();
        }

        [HttpPost]
        public ActionResult SaveAddPackage(Packages packages, HttpPostedFileBase TourPic)
        {
            Random rnd = new Random();
            var extensions = "";
            var allowExtensions = new[]
            {
                ".jpg",".Jpg",".png",".jpeg"
            };
            if (TourPic != null)
            {
                extensions = Path.GetExtension(TourPic.FileName);
            }
         
            if (allowExtensions.Contains(extensions))
            {
                int filelength = 0;
                filelength = TourPic.ContentLength;
                if (filelength > 307200)
                {
                    TempData["msg"] = "Image size must be less than or equal to 300KB";
                    return RedirectToAction("AddPackage");
                }
                else
                {
                    if (packages.PackageID == 0)
                    {
                        string filename = "";
                        filename = TourPic.FileName;
                        var dt = DateTime.Now.ToString("ddmmyyyy");
                        if (extensions == ".jpg")
                        {
                            var pp7 = rnd.Next(4, 9999).ToString();
                            TourPic.SaveAs(HttpContext.Server.MapPath("~/img/") + pp7 + dt + ".jpg");
                            packages.TourPic = pp7 + dt + ".jpg";
                        }
                        else if (extensions == ".jpeg")
                        {
                            var pp7 = rnd.Next(4, 9999).ToString();
                            TourPic.SaveAs(HttpContext.Server.MapPath("~/img/") + pp7 + dt + ".jpeg");
                            packages.TourPic = pp7 + dt + ".jpeg";
                        }
                        else if (extensions == ".Jpg")
                        {
                            var pp7 = rnd.Next(4, 9999).ToString();
                            TourPic.SaveAs(HttpContext.Server.MapPath("~/img/") + pp7 + dt + ".Jpg");
                            packages.TourPic = pp7 + dt + ".Jpg";
                        }
                        else if (extensions == ".png")
                        {
                            var pp7 = rnd.Next(4, 9999).ToString();
                            TourPic.SaveAs(HttpContext.Server.MapPath("~/img/") + pp7 + dt + ".png");
                            packages.TourPic = pp7 + dt + ".png";
                        }

                        int i = _travellerRepositoris.UserSaveAddPackage(packages);
                        TempData["msg"] = "Save Successfully";
                    }
                    else
                    {
                        string filename = "";
                        filename = TourPic.FileName;
                        var dt = DateTime.Now.ToString("ddmmyyyy");
                        if (extensions == ".jpg")
                        {
                            var pp7 = rnd.Next(4, 9999).ToString();
                            TourPic.SaveAs(HttpContext.Server.MapPath("~/img/") + pp7 + dt + ".jpg");
                            packages.TourPic = pp7 + dt + ".jpg";
                        }
                        else if (extensions == ".jpeg")
                        {
                            var pp7 = rnd.Next(4, 9999).ToString();
                            TourPic.SaveAs(HttpContext.Server.MapPath("~/img/") + pp7 + dt + ".jpeg");
                            packages.TourPic = pp7 + dt + ".jpeg";
                        }
                        else if (extensions == ".Jpg")
                        {
                            var pp7 = rnd.Next(4, 9999).ToString();
                            TourPic.SaveAs(HttpContext.Server.MapPath("~/img/") + pp7 + dt + ".Jpg");
                            packages.TourPic = pp7 + dt + ".Jpg";
                        }
                        else if (extensions == ".png")
                        {
                            var pp7 = rnd.Next(4, 9999).ToString();
                            TourPic.SaveAs(HttpContext.Server.MapPath("~/img/") + pp7 + dt + ".png");
                            packages.TourPic = pp7 + dt + ".png";
                        }
                        int i = _travellerRepositoris.UpdateAddPackage(packages);
                        TempData["msg"] = "Save Successfully";
                    }
                }
            }
            return RedirectToAction("AddPackage");
        }

        public ActionResult ManageAddPackage()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DeleteManageAddPackage(int? packageID)
        {
            int i = 0;
            if (packageID != null)
            {
                i = _travellerRepositoris.DeleteAddPackage(packageID);
                if (i > 0)
                {
                    TempData["msg"] = "Data Delete Succeccfully....";
                }
                else
                {
                    TempData["msg"] = "! there is problem no data delete";
                }
            }
            return RedirectToAction("ManageAddPackage");
        }
    }
}

Application.TourAndTravel.Web/Views/Traveller/Leads.cshtml
@model IEnumerable<Application.TourAndTravel.BookingInfo>
@using Application.TourAndTravel.Web.Models
@{
    ViewBag.Title = "Leads";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
    DBAccessVM dBAccessVM = new DBAccessVM();
    TravellerRepositoris travellerRepositoris = new TravellerRepositoris();

    long count = 0;
    string userName = string.Empty;
    if (User.Identity.IsAuthenticated)
    {
        userName = User.Identity.Name;
    }
    bool xy = travellerRepositoris.CheckWalletAmount(userName);
}

<div class="row">
    <div id="message">
        @if (TempData["msg"] != null)
        {
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>Information!</strong> @TempData["msg"]
            </div>
        }

    </div>
    @foreach (var data in Model)
    {
        int _leadCount = dBAccessVM.isLeadGenerated.Where(a => a.LeadID == data.BookingInfoID).Select(a => a.SoldLeadCount).Count();
        count = dBAccessVM.isLeadGenerated.Where(a => a.TravellerUserName == userName && a.LeadID == data.BookingInfoID).Select(a => a.LeadID).FirstOrDefault();
        <div class="col-sm-6">
            <div class="panel panel-bd lobidrag">

                <div class="panel-body">

                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <tbody>
                                <tr class="alert alert-info">
                                    <td>Lead ID</td>
                                    <td>@data.BookingInfoID</td>

                                    <td>Date</td>
                                    <td>@data.CreatedDate.ToString("dd MMM, yyyy")</td>
                                </tr>
                                <tr>
                                    <td>No of Adults and Kids (Adults/Kids)</td>
                                    <td colspan="3"><strong>@data.NoOfAdults</strong> Adults and <strong>@data.NoOfKids</strong> Kids</td>
                                </tr>
                                <tr>
                                    <td>Destination</td>
                                    <td colspan="3">@data.Destination</td>
                                </tr>
                                <tr>
                                    <td>Duration</td>
                                    <td colspan="3">@data.Duration</td>
                                </tr>
                                <tr>
                                    <td>Departure Date</td>
                                    <td colspan="3">@data.DepartureDate.ToString("dd MMMM, yyyy")</td>
                                </tr>
                                <tr>
                                    <td>Name</td>
                                    <td colspan="3"><span style="color:red">xxxxxxxxxx</span></td>
                                </tr>
                                <tr>
                                    <td>Email ID</td>
                                    <td colspan="3"><span style="color:red">xxxxxxxxxx</span></td>
                                </tr>
                                <tr>
                                    <td>Mobile No</td>
                                    <td colspan="3"><span style="color:red">xxxxxxxxxx</span></td>
                                </tr>
                                <tr>
                                    <td>Requirements</td>
                                    <td colspan="3">@data.Requirements</td>
                                </tr>
                                <tr>
                                    <td colspan="4">
                                        <address class="text-right">
                                            <b>Price ₹ : <span id="ContentPlaceHolder1_repeter1_lbprice_0" style="color:Blue;">75</span></b><br>
                                            <form action="/Traveller/SellLead" method="post">
                                                <input type="hidden" id="leadID" name="leadID" value="@data.BookingInfoID" />
                                                @if (xy != true)
                                                {
                                                    <button type="button" class="btn btn-primary disabled">Recharge your wallet</button><br />
                                                    <small style="color:red">You have insufficent balance, you have minimum 75 rupees only to buy this lead.</small>
                                                }
                                                else if (_leadCount >= 3)
                                                {
                                                    <button type="button" class="btn btn-danger disabled">Sold Out</button>
                                                }
                                                else if (count != 0)
                                                {
                                                    <button type="button" title="You have already purchased this lead." class="btn btn-danger disabled">Sold Out</button>
                                                }
                                                else
                                                {
                                                    <button type="submit" class="btn btn-primary">Buy Now</button>
                                                }
                                            </form>

                                        </address>
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    }

</div>

Application.TourAndTravel.Web/Views/Traveller/ManageAddPackage.cshtml
@using Application.TourAndTravel.Web.Models
@{ 
    DBAccessVM dal = new DBAccessVM();
}
@{
    ViewBag.Title = "ManageAddPackage";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-bd lobidrag">
                    <div class="panel-heading">
                        <div class="btn-group" id="buttonexport">
                            <a href="javascript:void">
                                <h4>Manage Package</h4>
                            </a>
                        </div>
                    </div>
                    <div class="panel-body">
                        <!-- Plugin content:powerpoint,txt,pdf,png,word,xl -->
                        <div class="btn-group">
                            <div class="buttonexport" id="buttonlist">
                                <a class="btn btn-add" href="/Traveller/AddPackage">
                                    <i class="fa fa-plus"></i>Add New Package
                                </a>
                            </div>
                          
                        </div>
                        <!-- Plugin content:powerpoint,txt,pdf,png,word,xl -->
                        <div class="table-responsive">
                            <table id="dataTableExample1" class="table table-bordered table-striped table-hover">
                                <thead>
                                    <tr class="info">
                                        <th>SL</th>
                                        <th>Photo</th>
                                        <th>Tour Type</th>
                                        <th>Duration</th>
                                        <th>Meal Plan</th>
                                        <th>Price</th>
                                        <th>Create Date</th>                                    
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{ 
                                        int sr = 0;
                                    }@{
                                        //var coll = dal.PackagesByAdmin.Where(a => a.IsDelete == false).ToList();
                                        var coll = dal.Package.Where(a=>a.IsDelete==false).ToList();
                                        foreach (var m in coll)
                                        {
                                            <tr>
                                                <td>@{sr++;}@sr</td>
                                                <td><img src="~/img/@m.TourPic" class="img-circle" alt="User Image" width="50" height="50"> </td>
                                                <td>@m.TourType</td>
                                                <td>@m.Duration</td>
                                                <td>@m.MealPlan</td>
                                                <td>@m.TotalPrice</td>
                                                <td>@m.CreatedDate</td>                                             
                                                <td>
                                                    <span class="label-custom label label-default">
                                                        @if (m.IsDelete == true)
                                                    {
                                                        <span>Yes</span>
                                                    }
                                                    else
                                                    {
                                                        <span>No</span>
                                                    }
                                                </span>
                                            </td>
                                                <td>
                                                    <a href="@Url.Action("AddPackage","Traveller", new { packageID=m.PackageID})" class="btn btn-xs btn-info"><i class="fa fa-pencil-square"></i></a>
                                                    <a href="@Url.Action("DeleteManageAddPackage","Traveller", new { packageID=m.PackageID})" class="btn btn-xs btn-danger"><i class="fa fa-trash-o"></i></a>
                                                  
                                                </td>
                                            </tr>
                                        }

                                    }
                                    
                                 
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
   

Application.TourAndTravel.Web/Views/Traveller/MyLeads.cshtml
@model IEnumerable<Application.TourAndTravel.BookingInfo>
@{
    ViewBag.Title = "MyLeads";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}
<div class="row">
    <div id="message">
        @if (TempData["msg"] != null)
        {
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>Information!</strong> @TempData["msg"]
            </div>
        }

    </div>
    @foreach (var data in Model)
    {
        <div class="col-sm-6">
            <div class="panel panel-bd lobidrag">

                <div class="panel-body">

                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <tbody>
                                <tr class="alert alert-info">
                                    <td>Lead ID</td>
                                    <td>@data.BookingInfoID</td>

                                    <td>Date</td>
                                    <td>@data.CreatedDate.ToString("dd MMM, yyyy")</td>
                                </tr>
                                @*<tr>
                                    <td>No of Adults and Kids (Adults/Kids)</td>
                                    <td colspan="3"><strong>@data.NoOfAdults</strong> Adults and <strong>@data.NoOfKids</strong> Kids</td>
                                </tr>
                                <tr>
                                    <td>Destination</td>
                                    <td colspan="3">@data.Destination</td>
                                </tr>*@
                                <tr>
                                    <td>Duration</td>
                                    <td colspan="3">@data.Duration</td>
                                </tr>
                                @*<tr>
                                    <td>Departure Date</td>
                                    <td colspan="3">@data.DepartureDate.ToString("dd MMMM, yyyy")</td>
                                </tr>*@
                                <tr>
                                    <td>Name</td>
                                    <td colspan="3">@data.ClientName</td>
                                </tr>
                                <tr>
                                    <td>Email ID</td>
                                    <td colspan="3">@data.Email</td>
                                </tr>
                                <tr>
                                    <td>Mobile No</td>
                                    <td colspan="3">@data.MobileNo</td>
                                </tr>
                                @*<tr>
                                    <td>Requirements</td>
                                    <td colspan="3">@data.Requirements</td>
                                </tr>*@
                                
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    }

</div>

Application.TourAndTravel.Web/Views/Traveller/SignUp.cshtml
@model Application.TourAndTravel.TravellerRegistration
@{
    ViewBag.Title = "SignUp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- blog breadcrumb version one strat here -->
<section class="breadcrumb-blog-version-one">
    <div class="single-bredcurms" style="background-image:url('../../Assets/images/bercums/contact-page.jpg');">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="bredcrums-content">
                        <h2>Traveller Registration</h2>
                        <ul>
                            <li><a href="#">Home</a></li>
                            <li class="active"><a href="#">Traveller Registration</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- blog breadcrumb version one end here -->


<section class="section-paddings">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="contact-title">
                    <h2>Traveller Sign Up</h2>
                </div>
                <div class="address">
                    <p>
                        <br>If you have already an account. Please <a href="#" class="btn btn-primary">Login</a>
                    </p>
                </div>
                <div>
                    <img src="~/Assets/images/signup-here.png" />
                </div>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="contact-title">
                    <h2>Fill your information</h2>
                </div>
                <div class="contact-form">
                    <div id="contact">
                        <div id="message">
                            @if (TempData["msg"] != null)
                            {
                                <div class="alert alert-success alert-dismissable">
                                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                                    <strong>Information!</strong> @TempData["msg"]
                                </div>
                            }

                        </div>
                        <!-- Contact Form -->
                        @using (Html.BeginForm("SignUp", "Traveller", FormMethod.Post))
                        {
                            @Html.HiddenFor(a => a.TravellerID);
                            @Html.ValidationSummary(true);
                            <div class="row form-group">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        @Html.TextBoxFor(a => a.TravellerCompanyName, new { @placeholder = "Enter Company Name", @required = "" })
                                        @Html.ValidationMessageFor(a => a.TravellerCompanyName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        @Html.TextBoxFor(a => a.TravellerName, new { @placeholder = "Enter Your Name", @required = "" })
                                        @Html.ValidationMessageFor(a => a.TravellerName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="row form-group">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        @Html.TextBoxFor(a => a.TravellerMobileNo, new { @placeholder = "Enter Mobile No", @required = "" })
                                        @Html.ValidationMessageFor(a => a.TravellerMobileNo, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        @Html.TextBoxFor(a => a.TravellerEmail, new { @placeholder = "Enter Email ID", @type = "email", @required = "" })
                                        @Html.ValidationMessageFor(a => a.TravellerEmail, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="row form-group">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        @Html.TextBoxFor(a => a.TravellerGSTIN_No, new { @placeholder = "Enter GSTIN No", @required = "" })
                                        @Html.ValidationMessageFor(a => a.TravellerGSTIN_No, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        @Html.TextBoxFor(a => a.TravellerPAN_No, new { @placeholder = "Enter PAN No", @required = "" })
                                        @Html.ValidationMessageFor(a => a.TravellerPAN_No, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.PasswordFor(a => a.TravellerPassword, new { @placeholder = "Enter Password", @required = "" })
                                @Html.ValidationMessageFor(a => a.TravellerPassword, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                @Html.TextAreaFor(a => a.TravellerAddress, new { @placeholder = "Enter Address...", @required = "" })
                                @Html.ValidationMessageFor(a => a.TravellerAddress, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group text-right">
                                <button type="submit" class="btn btn-success"><i class="fa fa-sign-in"></i> Registration</button>
                            </div>
                        }
                        <!--/ End Contact Form -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="~/Assets/js/vendor/jquery-3.2.0.min.js"></script>
<script src="~/Assets/js/JQueryValidate/jquery.validate.min.js"></script>
<script src="~/Assets/js/JQueryValidate/jquery.validate.unobtrusive.min.js"></script>